tab = read.table("http://www.math.uni.wroc.pl/~mbogdan/Podstawy/Dane/individuals.dat")
#table(tab[[3]])
#pie(table(tab[[3]]))
tab[[3]] = as.factor(tab[[3]])
levels(tab[[3]]) = c("podstawowe", "zawodowe", "średnie", "szkoła\npomaturalna", "licencjat", "wyższe")
tab[[6]] = as.factor(tab[[6]])
levels(tab[[6]]) = c("sektor prywatny", "sektor rządowy", "samo-zatrudnienie")
#round(table(tab[[3]])/dim(tab[1])*100)
#paste(levels(tab[[3]]), ", (", round(table(tab[[3]])/dim(tab[3])[1]*100), "%)", sep = "")
pie(table(tab[[3]]), labels = paste(levels(tab[[3]]), ", (", round(table(tab[[3]])/dim(tab[3])[1]*100), "%)", sep = ""))
males = subset(tab, tab[4] == 1)
females = subset(tab, tab[4] == 2)
par(mfrow=c(4,2))
pie(table(males[[3]]), labels = paste(levels(males[[3]]), ", (", round(table(males[[3]])/dim(males[3])[1]*100), "%)", sep = ""))
pie(table(females[[3]]), labels = paste(levels(females[[3]]), ", (", round(table(females[[3]])/dim(females[3])[1]*100), "%)", sep = ""))
by(tab[[5]], tab[[3]], mean)

by(tab[[5]], paste(tab[[3]], ", ", tab[[6]], sep = ""), mean)
barplot(by(tab[[5]], paste(tab[[3]], ", ", tab[[6]], sep = ""), mean), las =2, cex.names = 0.5)
hist(tab[[5]])
c(mean(tab[[5]]), median(tab[[5]]), mean(tab[[5]])/median(tab[[5]]))
ld = log(tab[5][tab[5]> 0])
hist(ld)
ld
c(mean(ld), median(ld), mean(ld)/median(ld))
par(mfrow = c(1,2))
plot(males[[2]], males[[5]])
plot(females[[2]], females[[5]])
